name: Lint

on: [push, pull_request]

jobs:
  JS-Lint:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm i
      - name: Run Lint
        run: ./node_modules/eslint/bin/eslint.js --output-file eslint_report.json --format json .
        continue-on-error: true
      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          report-json: "eslint_report.json"
      - name: Store ESLint report
        uses: actions/upload-artifact@v1
        with:
          name: eslint_report.json
          path: eslint_report.json

  PHP-Lint:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@master
      - name: Install Dependencies
        run: |
          composer global require "squizlabs/php_codesniffer=*"
          composer global require wp-coding-standards/wpcs
          composer require staabm/annotate-pull-request-from-checkstyle
          composer require php-parallel-lint/php-parallel-lint
      - name: Run Lint
        run: |
          export PATH=$HOME/.composer/vendor/bin:$PATH
          phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
          phpcs -q -n . --standard=./ruleset.xml --report=checkstyle --extensions=php | vendor/bin/cs2pr
      - name: Run PHP Syntax Lint
        run: |
          export PATH=$HOME/.composer/vendor/bin:$PATH
          php5.6 vendor/bin/parallel-lint --checkstyle --blame --exclude node_modules --exclude vendor . | vendor/bin/cs2pr
          php7.0 vendor/bin/parallel-lint --checkstyle --blame --exclude node_modules --exclude vendor . | vendor/bin/cs2pr
          php7.1 vendor/bin/parallel-lint --checkstyle --blame --exclude node_modules --exclude vendor . | vendor/bin/cs2pr
          php7.2 vendor/bin/parallel-lint --checkstyle --blame --exclude node_modules --exclude vendor . | vendor/bin/cs2pr
          php7.3 vendor/bin/parallel-lint --checkstyle --blame --exclude node_modules --exclude vendor . | vendor/bin/cs2pr
